### ISSUE TITLE
nuget package - wondering if someone will ever create a nuget package for d3.js :)

### ISSUE THREAD

**Issue by bjm3819** [d3/d3.github.com#2]

**Comment by mbostock** [comment]
This should probably have been put into the mbostock/d3 issues. Per the [D3 wiki](https://github.com/mbostock/d3/wiki#installing):

> D3 is also available via numerous package managers, including: [NPM](https://npmjs.org/package/d3) (Node.js), [Bower](http://bower.io/search/?q=d3), [Browserify](http://browserify.org/), [Component](http://component.io/), [Jam](http://jamjs.org/packages/#/details/d3), [Composer / Packagist](https://packagist.org/packages/mbostock/d3) (PHP), [SPM](https://spmjs.org/gallery/d3/), [JSPM](http://jspm.io/), [NuGet](https://www.nuget.org/packages/d3/) (.Net), and [AMD](https://github.com/amdjs/amdjs-api/blob/master/AMD.md) (e.g., [RequireJS](http://requirejs.org/)). The official releases of D3 are on [NPM](https://npmjs.org/package/d3) and [GitHub](/mbostock/d3) only; support for other package managers is unofficial and maintained by contributors.
